#include "main.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "gba.h"
#include "hangman.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

#include "images/hangman_home.h"
#include "images/hangman_word.h"
#include "images/hangman_play.h"
#include "images/hangman_win.h"
#include "images/hangman_lose.h"
#include "images/hangman_spin1.h"
#include "images/hangman_spin2.h"
#include "images/hangman_spin3.h"
#include "images/hangman_spin4.h"
#include "images/hangman_spin5.h"
#include "images/hangman_spin6.h"
#include "images/hangman_spin7.h"
#include "images/hangman_spin8.h"
#include "images/hangman_spin9.h"
#include "images/hangman_spin10.h"
#include "images/hangman_spin11.h"
#include "images/hangman_spin12.h"
#include "images/hangman_missing.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WORD,
  WIN,
  LOSE,
};

// Stores number of vblanks (cycles through the while loop)
int num_vblanks;


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Set to 1 during phase 1 if the game is won or lost to let phase 2-3 know to update
  int gameWon = 0;
  int gameLost = 0;

  // Load initial application state
  enum gba_state state = START;
  enum gba_state prevState = START;

  // Contains info about the user's word
  struct word enteredWord;
  enteredWord.wordPos = 80;
  enteredWord.numLetters = 0;

  // Contains info about the user's incorrect guesses
  struct wrongGuesses incorrect;
  incorrect.numIncorrect = 0;
  incorrect.wrongLetter = 0;

  // Contains info about the box used to select letters and the letter select
  struct boxLetter box;
  box.letterChosen = 0;
  box.shiftBox = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    num_vblanks++;
    box.shiftBox = 0;
    box.letterChosen = 0;
    incorrect.wrongLetter = 0;

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        // Resets game & all variables
        box.letterChosen = 0;
        incorrect.wrongLetter = 0;
        gameWon = 0;
        gameLost = 0;
        box.shiftBox = 0;
        incorrect.numIncorrect = 0;
        enteredWord.numLetters = 0;
        enteredWord.wordPos = 80;
        for (int i = 0; i < 6; i++) {
          incorrect.wrongGuessPositions[i].x = 0;
          incorrect.wrongGuessPositions[i].y = 0;
        }
        
        break;
      case PLAY:
        // Checks if box should be shifted or letter is guessed
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
          box.letterChosen = 1;
          box.letter = letterSelected(box.boxPosition.x, box.boxPosition.y, 1);
          int status = enterLetter(enteredWord.word, enteredWord.blanks, box.letter);
          if (status == 0) {
            incorrect.wrongGuessPositions[incorrect.numIncorrect].x = box.boxPosition.x;
            incorrect.wrongGuessPositions[incorrect.numIncorrect].y = box.boxPosition.y;
            incorrect.numIncorrect++;
            incorrect.wrongLetter = 1;
          } else if (status == 3) {
            gameWon = 1;
          }
        }

        break;
      case WORD:
        // Checks if box should be shifted or letter is guessed
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          box.shiftBox = 1;
        } else if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
          box.letterChosen = 1;
          box.letter = letterSelected(box.boxPosition.x, box.boxPosition.y, 0);
          enteredWord.word[enteredWord.numLetters] = box.letter;
          enteredWord.numLetters++;
        } else if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
          box.letterChosen = 1;
          box.letter = ' ';
          enteredWord.word[enteredWord.numLetters] = box.letter;
          enteredWord.numLetters++;
        }
        
        break;
      case WIN:

        break;
      case LOSE:

        break;
    }

    waitForVBlank();

    switch (state) {
      case START:
        // Draws start screen and cycles through animation (stick figure spinning in circle)
        if (num_vblanks < 4 || prevState == WORD || prevState == PLAY || prevState == WIN || prevState == LOSE) {
            drawFullScreenImageDMA(hangman_home);
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            num_vblanks = 120;
        } else if (num_vblanks < 3 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin1);
        } else if (num_vblanks < 4 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin2);
        } else if (num_vblanks < 5 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin3);
        } else if (num_vblanks < 6 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin4);
        } else if (num_vblanks < 7 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin5);
        } else if (num_vblanks < 8 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin6);
        } else if (num_vblanks < 9 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin7);
        } else if (num_vblanks < 10 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin8);
        } else if (num_vblanks < 11 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin9);
        } else if (num_vblanks < 12 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin10);
        } else if (num_vblanks < 13 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin11);
        } else if (num_vblanks < 14 * 60) {
            drawImageDMA(52, 73, 50, 65, hangman_missing);
            drawImageDMA(52, 73, 50, 65, hangman_spin12);
        } else {
            num_vblanks = 120;
        }

        break;
      case PLAY:
        if (prevState == WORD) {
          // Sets screen for word guessing stage
          wordToOutput(enteredWord.word, enteredWord.blanks);
          drawFullScreenImageDMA(hangman_play);
          box.boxPosition.x = 111;
          box.boxPosition.y = 8;
          drawRectDMA(box.boxPosition.x, box.boxPosition.y, 14, 14, MAGENTA);
          undrawImageDMA(box.boxPosition.x + 1, box.boxPosition.y + 1, 12, 12, hangman_play);
          drawCenteredString(92, 0, 240, 10, enteredWord.blanks, GRAY);
        }

        if (box.shiftBox == 1) {
          // Shifts box in direction of arrow pressed
          box.boxPosition = moveBox(box.boxPosition.x, box.boxPosition.y, currentButtons, previousButtons, incorrect.numIncorrect, incorrect.wrongGuessPositions);
        } else if (box.letterChosen == 1) {
            if (incorrect.wrongLetter == 1) {
              // Draws a limb on the hangman, blacks out the letter guessed, moves the box to the right 1, and adds incorrect guess to array
              gameLost = drawBodyPart(incorrect.numIncorrect);
              box.boxPosition = incorrectGuess(box.boxPosition.x, box.boxPosition.y, incorrect.numIncorrect, incorrect.wrongGuessPositions);
            } else {
              // Redraws the word with correct letter showing
              undrawImageDMA(92, 18, 200, 15, hangman_play);
              drawCenteredString(92, 0, 240, 10, enteredWord.blanks, GRAY);
            }
        }

        break;
      case WORD:
        // Draws word screen
        if (prevState == START) {
          drawFullScreenImageDMA(hangman_word);
          box.boxPosition.x = 108;
          box.boxPosition.y = 8;
          drawRectDMA(box.boxPosition.x, box.boxPosition.y, 14, 14, MAGENTA);
          undrawImageDMA(box.boxPosition.x + 1, box.boxPosition.y + 1, 12, 12, hangman_word);
        }
        // Shifts box in direction of array
        if (box.shiftBox == 1) {
          box.boxPosition = moveBoxWord(box.boxPosition.x, box.boxPosition.y, currentButtons, previousButtons);
        } else if (box.letterChosen == 1) {
          // Adds letter to word string
          drawChar(70, enteredWord.wordPos, enteredWord.word[enteredWord.numLetters - 1], BLACK);
          enteredWord.wordPos += 10;
        }
        break;
      case WIN:
        // Draws win screen
        drawFullScreenImageDMA(hangman_win);

        break;
      case LOSE:
        // Draws lose screen
        drawFullScreenImageDMA(hangman_lose);

        break;
    }

    prevState = state;

    switch (state) {
      case START:
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = WORD;
        }
        
        break;
      case PLAY:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        } else if (gameWon == 1) {
          state = WIN;
        } else if (gameLost == 1) {
          state = LOSE;
        }

        break;
      case WORD:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        } else if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          enteredWord.word[enteredWord.numLetters] = '\0';
          state = PLAY;
        }

        break;
      case WIN:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }

        break;
      case LOSE:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }

        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
